name: anagram
version: 1.1.0.5

dependencies:
  - base

library:
  exposed-modules: Anagram
  source-dirs: src
  dependencies:
    - multiset >=0.3.3
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - anagram
      - hspec
